### ISSUE TITLE
如何在外地播放广东的直播学习频道?

### ISSUE THREAD

**Issue by iranee** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#1]
本人在外省，需要播放广东IPTV直播的电视节目供学生观看。
现在的条件是可以ssh进路由器，用什么办法可以获取完整的直播源？

**Comment by Tzwcard** [comment]
组播源异地播放都比较麻烦
一个就是用udpxy转成http流再把端口映射出去播 要安全点就内网做个反向代理再映射出去
另一个就是走隧道回内网再放组播源 我目前是没找到什么能用的隧道协议 不过听说GRE隧道可以 我是没试过就是了
实在急需看教育节目的话 我搜了下 广州教育11个台广视网首页有portal 粤课堂好像有个手机app可以看 百视通学而思的话他们自家的app好像也能看

**Comment by iranee** [comment]
谢谢答疑。现在有手机app可以用，主要是手机和网页端跟电视的IPTV不同步而且电视可以一次性播放完，手机端分段播放。

**Comment by AnsonChou** [comment]
打不开了

**Comment by AnsonChou** [comment]
之前还可以用，这两天用PotPlayer打开无法播放

**Comment by AnsonChou** [comment]
之前用PotPlayer都可以播放，这两天用PotPlayer打开无法播放

**Comment by Tzwcard** [comment]
> 之前用PotPlayer都可以播放，这两天用PotPlayer打开无法播放

刚才试了下没什么问题
https://imgur.com/a/kAP9o3g
有可能是你IPTV的PPPoE断了 我这边（沙湾）只要不小心把路由重启或者把IPTV的PPP重拨都会有几率播不了组播源
解决方法是放几天让电信自动把你踢下线 或者试试光猫和路由断电一会之后再开 起码我找不到稳定的方法让它能每次都恢复组播

**Comment by jimly1032** [comment]
你好，广东地区内都可以用吗？我用potplayer打不开、vlc也是

**Comment by Tzwcard** [comment]
> 你好，广东地区内都可以用吗？我用potplayer打不开、vlc也是

试试电脑直接连iTV口直接PPPoE拨IPTV的账号密码 再打开组播地址
如果不行的话光猫断电几秒再试试 不行就没办法了
能播的话再看看igmpproxy转发itv上游到局域网下游 或者udpxy之类的软件把组播流转http流播放
