### ISSUE TITLE
兄弟，广州好像看不了

### ISSUE THREAD

**Issue by star8618** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#10]
自己架设了udpxy，还是无法观看

**Comment by Tzwcard** [comment]
![udpxy_status](https://user-images.githubusercontent.com/12098388/140617008-76c0883f-a7a4-4bc3-b7bd-b88ccef104a3.png)
我在广州好着呢
你可以上网找一下具体教程或者其他解决方法 这里只提供列表 其他不管的

**Comment by tanxianbo** [comment]
光猫要开启IGMP支持（超级管理员登录），否则无法访问
