### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by nokia197s** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#12]
求教EPG怎么做的，，

**Comment by Tzwcard** [comment]
CNTV API:
`https://api.cntv.cn/epg/getEpgInfoByChannelNew?c={$chname}&serviceId={$service}&d={$date}&t=json`
- $service: cboxclient / tvcctv
- $chname: 频道名
- $date: 日期（Ymd）

GRT API:
`http://epg.gdtv.cn/f/{$chid}/{$date}.xml`
- $chid: 频道编号
- $date: 日期（Y-m-d）

**Comment by fqx** [comment]
可以顺便说一下 http://epg.51zmt.top:8000/api/diyp/ 这个API怎么调用吗？

**Comment by fqx** [comment]
哦，我查到了，就是 
`http://epg.51zmt.top:8000/api/diyp/?ch={name}&date={date}`
那么，没有API可以像 http://epg.51zmt.top:8000 网页那样加上LOGO吗？
