### ISSUE TITLE
RTSP 地址

### ISSUE THREAD

**Issue by xxhg** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#13]
你好，可以把 RTSP 地址也贴出来吗，也许有人可以看。

**Comment by Tzwcard** [comment]
**请看readme.md**

**Comment by xxhg** [comment]
有验证消息也有办法可以看。

**Comment by Tzwcard** [comment]
是带“我自己”的用户信息，我知道rtsp在其他地方也可以看，谢谢。

**Comment by xxhg** [comment]
> 

所以你可以把 RTSP 地址贴出来吗？
具体方法我还不知道，我等拿到地址了再找办法看。
