### ISSUE TITLE
老师，请问你这些文件是用什么软件才能播放呀

### ISSUE THREAD

**Issue by rufan321** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#17]
老师，请问你这些文件是用什么软件才能播放呀

**Comment by Tzwcard** [comment]
你有广东电信的IPTV服务的话一般用udpxy转发下就能播了

**Comment by tanxianbo** [comment]
光猫要开启IGMP支持（超级管理员登录），否则无法访问

**Comment by fqx** [comment]
> 你有广东电信的IPTV服务的话一般用udpxy转发下就能播了

为啥我总是放到250秒左右就没下行数据了？
