### ISSUE TITLE
关于如何抓取最新IGMP地址

### ISSUE THREAD

**Issue by fanvinga** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#2]
请问一下在Wireshark里面找到getChannelList的这个POST请求之后在哪里能找到需要的地址json?

**Comment by fanvinga** [comment]
已解决

**Comment by jikkyfu** [comment]
你好，我用华为的管理工具抓包，现在生成的只有RTSP，IGMP没有了。
你是用什么方式抓到的能否告知？

**Comment by jikkyfu** [comment]
> 已解决

你好，我用华为的管理工具抓包，现在生成的只有RTSP，IGMP没有了。
你是用什么方式抓到的能否告知？

**Comment by tanxianbo** [comment]
我用几年前的节点访问有IGMP，意思就是旧的节点有IGMP，现在盒子都是默认加载新节点
