### ISSUE TITLE
请问一下，rtsp回放在播放时没办法拖进度条要怎么解决？

### ISSUE THREAD

**Issue by VergilGao** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#22]
现在就差这么一个问题就能完美覆盖掉我的iptv盒子了……

**Comment by jackiezh** [comment]
应该是播放器问题吧。你是广东电信的吗？广东电信rtsp应该已经全军覆没了吧

**Comment by VergilGao** [comment]
> 应该是播放器问题吧。你是广东电信的吗？广东电信rtsp应该已经全军覆没了吧

长春电信，就没找到任何一个能拖进度条的播放器……

**Comment by Tzwcard** [comment]
拖动进度条等于请求回放 rtsp回放需要加&playseek=yyyymmddhhiiss-yyyymmddhhiiss
这个你要看看哪个播放器支持这么拖动的 据我所知暂时没有

**Comment by VergilGao** [comment]
https://github.com/xbmc/inputstream.ffmpegdirect/issues/232

已解决。

方案是在kodi的m3u文件里，每一个流加上 `#KODIPROP:inputstream=inputstream.ffmpegdirect`

**Comment by kery** [comment]
> [xbmc/inputstream.ffmpegdirect#232](https://github.com/xbmc/inputstream.ffmpegdirect/issues/232)
> 
> 已解决。
> 
> 方案是在kodi的m3u文件里，每一个流加上 `#KODIPROP:inputstream=inputstream.ffmpegdirect`

解决了我的大问题！

**Comment by c1pher-cn** [comment]
请问一下你的kodi里回放的时间参数是怎么设置的？

**Comment by VergilGao** [comment]
> 请问一下你的kodi里回放的时间参数是怎么设置的？

playseek={utc:YmdHMS}-{end:YmdHMS}

**Comment by c1pher-cn** [comment]
感谢，再问下你的源  你融合是配置的udpxy转的组播？ 还是igmp单播？

**Comment by VergilGao** [comment]
> 感谢，再问下你的源 你融合是配置的udpxy转的组播？ 还是igmp单播？

我家是长春电信，他们的 iptv 提供两个源，其中直播是组播源，回放是单播源。
其实直播也可以看单播源，但是这样我亲测对比组播源有一两秒延迟。
所以我直播用的是udpxy转的组播，然后回放用igmp单播。

https://github.com/VergilGao/Telecom-IPTV-Mock/blob/0d3fa80400ca777662db24bac12dfc3050cf219d/src/stbmock.py#L190
