### ISSUE TITLE
昨晚路由重启后就不行了访问就是这种情况，是组播地址失效了吗？

### ISSUE THREAD

**Issue by zhu-jie** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#29]
25197	192.168.31.44:36073	239.77.0.225:5146	N/A
有大佬能支支招吗？在路由器上使用tcpdump抓不到源

**Comment by Tzwcard** [comment]
试了一下广州电信今天能访问 可以试一下断电长一点时间再重新连接 itv interface

**Comment by zhu-jie** [comment]
谢谢，已经解决了，之前无法组播是由于op的路由表问题引起
