### ISSUE TITLE
广州电信有大佬指导下么，pppoe-IPTV都获取到ip了但就是播不了

### ISSUE THREAD

**Issue by flhs0606** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#34]
目前用的openwrt，看了很多教程，防火墙跟静态路由也设置了，折腾好几天没成功

**Comment by YCCCCCCCCC** [comment]
去山上问问

**Comment by zengkid** [comment]
@flhs0606 也许你可以试试用xteve配合plex来播放，我也是直接用电脑不行。不过用plex+xteve就可以了

**Comment by flhs0606** [comment]
最后自己折腾成功了。openwrt里面不能用iptv的账号密码拨号，虽然能拨号成功获取到ip，但就是播不了。用获取到的ip，接口设置成静态ip后就正常了。
