### ISSUE TITLE
关于AVS2编码

### ISSUE THREAD

**Issue by OptimusV5** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#6]
大佬，发现很多超清频道都是AVS2编码，大部分播放器打开都只有声音，请问有什么办法播放这些高清频道么？

**Comment by jikkyfu** [comment]
无解，这个需要解码支持。目前软件的解码还搞不定。只能依赖硬件。

**Comment by Tzwcard** [comment]
不是AVS2 是AVS+(CAVS)
网上有个魔改VLC能放AVS+ 可以搜一下
目前广东电信还没有一个台是AVS2的 估计也没那么快
记得AVS2是8K广播计划要用的 但是我估计到了IPTV不上源信号流的情况下也不会用上 应该最多和现在的综艺4K一样是HEVC
