### ISSUE TITLE
请问一下大佬能不能写一下国内其他的地方台好像 凤凰，贵州之类以后网上官网有直播的

### ISSUE THREAD

**Issue by a07119063** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#8]
**### 请问一下大佬能不能写一下国内其他的地方台好像 凤凰，贵州之类以后网上官网有直播的**

**Comment by Tzwcard** [comment]
我自己没有这个需求 所以不会去写
像我现在也有有线的UTV Box 打开就有新闻台和综艺台 还有凤凰台和凤凰香港 实在是不需要再去写
