### ISSUE TITLE
是不是开通IPTV才有播放权？

### ISSUE THREAD

**Issue by RoweV194** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#9]

**Comment by Tzwcard** [comment]
理论上说应该需要获取到itv的IP才能播放
我这里需要pppoe拨号才能获取到IP和看iptv
你可以试试自己把itv的VLAN ID和组播VLANID绑到光猫上未使用端口 然后直连一下看看rtp能不能播
我感觉按道理一般是不可以播的上的
